#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
def get_all_files(dir):
    files_ = []
    list = os.listdir(dir)
    for i in range(0, len(list)):
        path = os.path.join(dir, list[i])
        # print(path)
        if os.path.isdir(path):
            files_.extend(get_all_files(path))
        if os.path.isfile(path):
            files_.append(path.replace("D:\wamp\www\learn\python\wxPython\\", ""))
    return files_
print(get_all_files('D:\wamp\www\learn\python\wxPython'))
